---
title: Predictor Transformations Specification
---

## Introduction

Inputs for models used by the Algorithm Viewer may optionally be put through
various transformations before inputted into the model. Examples of transformations include centering, multiplying to
obtain interaction terms, and applying restricted cubic splines. The
transformations supported by the Algorithm Viewer, as well as how these
transformations are specified, should conform to the specifications in the
[Model Parameters](https://github.com/Big-Life-Lab/model-parameters)
repository.

This section specifies how all these transformations should be calculated. In
code, the implementation should represent all input variables and derived
variables in a single matrix, allowing transformation of multiple input vectors
with a single pass.

## Model Steps File

The steps involved for transforming the input data are specified in the [Model
Steps
File](https://big-life-lab.github.io/model-parameters/2-model-parameter-files.html#model-steps-file).
This file includes a list of steps along with a file path for the details
specific to that step. The steps are performed in sequence. Below is an example
Model Steps File:

| step        | fileType | filePath         |
|-------------|----------|------------------|
| dummy       | N/A      | dummy.csv        |
| rcs         | N/A      | rcs.csv          |
| interaction | N/A      | interactions.csv |
| center      | N/A      | center.csv       |
| logistic    | N/A      | logistic.csv     |

In the following sections, examples of the contents of the files specified in
the `filePath` column are shown.

## dummy Step

The [dummy
step](https://big-life-lab.github.io/model-parameters/2-model-parameter-files.html#dummy-step-file)
creates binary dummy variables from a categorical variable.

| origVariable | catValue | dummyVariable         |
|--------------|----------|-----------------------|
| smoker_type  | 0        | non_smoker            |
| smoker_type  | 1        | current_smoker        |
| smoker_type  | 2        | former_smoker         |

The above table can be expressed in code as:

```R
non_smoker <- as.integer(smoker_type == 0)
current_smoker <- as.integer(smoker_type == 1)
former_smoker <- as.integer(smoker_type == 2)
```

## center Step

The [center
step](https://big-life-lab.github.io/model-parameters/2-model-parameter-files.html#centering-step-file)
centers a variable by subtracting a center value.

| origVariable | centerValue | centeredVariable | centeredVariableType |
|--------------|-------------|------------------|----------------------|
| age          | 40          | age_C            | cont                 |
| diet_score   | 4           | diet_score_C     | cont                 |

The above table can be expressed in code as:

```R
age_C <- age - 40
diet_score_C <- diet_score - 4
```

## rcs Step

The [restricted cubic spline (rcs)
step](https://big-life-lab.github.io/model-parameters/2-model-parameter-files.html#restricted-cubic-spline-rcs-step-file)
applies a restricted cubic spline to a variable.

| variable | rcsVariables                              | knots              |
|----------|-------------------------------------------|--------------------|
| clc_age  | clc_age_rcs_1;clc_age_rcs_2;clc_age_rcs_3 | 24;40;57;74        |

The following code will apply the above RCS table to the input variable,
resulting in three new output variables (as specified in the `rcsVariables`
column):

```R
calculate_rcs <- function(x, knots) {
  # Number of knots
  nk <- length(knots)

  if (nk < 3) {
    stop("At least 3 knots required for RCS")
  }

  # Initialize matrix to store RCS terms
  # For nk knots, we get nk-1 terms total (1 linear + (k-2) restricted)
  n_terms <- nk - 1
  rcs_matrix <- matrix(NA, nrow = length(x), ncol = n_terms)

  # First term is just x
  rcs_matrix[, 1] <- x

  # Calculate additional restricted terms
  if (n_terms > 1) {
    # Knot positions
    t1 <- knots[1]
    tk_minus_1 <- knots[nk - 1]
    tk <- knots[nk]

    # Calculate terms 2 through (nk-2)
    for (j in 1:(n_terms - 1)) {
      tj <- knots[j]

      # Calculate the three cubic terms with truncation at zero
      term1 <- pmax((x - tj)^3 / (tk - t1)^2, 0)
      term2 <- pmax((x - tk)^3 / (tk - t1)^2 / (tk - tk_minus_1) * (tk_minus_1 - tj), 0)
      term3 <- pmax((x - tk_minus_1)^3 / (tk - t1)^2 / (tk - tk_minus_1) * (tk - tj), 0)

      rcs_matrix[, j + 1] <- term1 - term2 + term3
    }
  }

  return(rcs_matrix)
}

knots <- strsplit("24;40;57;74", ";")
knots <- as.numeric(unlist(knots))
rcs <- calculate_rcs(clc_age, knots)
clc_age_rcs_1 <- rcs[, 1]
clc_age_rcs_2 <- rcs[, 2]
clc_age_rcs_3 <- rcs[, 3]
```

## interaction Step

The [interaction
step](https://big-life-lab.github.io/model-parameters/2-model-parameter-files.html#interaction-step-file)
multiples two or more variables to get a new interaction variable.

| interactionVariable     | interactingVariables    | interactionVariableType |
|-------------------------|-------------------------|-------------------------|
| AgeXCancer              | Age;Cancer              | cont                    |
| AgeXCancerXHypertension | Age;Cancer;Hypertension | cont                    |

The above interaction table is represented in code as:

```R
AgeXCancer <- Age * Cancer
AgeXCancerXHypertension <- Age * Cancer * Hypertension
```

## logistic Step

The logistic step applies a logistic model to the existing variables. The
logistic equation has an intercept and coefficients for each variable. This
step is usually applied to the input variables after all transformations are
performed; it is equivalent to passing the variables into a logistic equation
to get a final output. In some cases, the user may instead want to pass the
transformed variables into an R model that performs the same operation. The
`Intercept` variable in the table below is a reserved word to represent the
intercept of the model.

| variable                   | coefficient |
|----------------------------|-------------|
| Intercept                  | 1           |
| clc_age_rcs_1_C            | 1.5         |
| clc_age_rcs_2_C            | -1          |
| clc_age_rcs_3_C            | 1           |
| diabx_1_C                  | 2           |
| clc_age_rcs_1_by_diabx_1_C | 0.1         |
| clc_age_rcs_2_by_diabx_1_C | -0.2        |
| clc_age_rcs_3_by_diabx_1_C | 3           |

The above logistic table is represented in code as:

```R
logistic_output <-
    1 +
    1.5 * clc_age_rcs_1_C +
    -1 * clc_age_rcs_2_C +
    1 * clc_age_rcs_3_C +
    2 * diabx_1_C +
    0.1 * clc_age_rcs_1_by_diabx_1_C +
    -0.2 * clc_age_rcs_2_by_diabx_1_C +
    3 * clc_age_rcs_3_by_diabx_1_C
```
